[alembic]
script_location = alembic
sqlalchemy.url = postgresql://postgres:postgres@db:5432/stackwise

[loggers]
logs = sys_log

[handlers]
sys_log = stdlib

[formatters]
generic = generic

[sys_log]
class = stream_handler
args = (sys.stdout,)
level = INFO
formatter = generic

[generic]
class = logging.Formatter
format = %(levelname)s: %(message)s
datefmt = %Y-%m-%d %H:%M:%S
